### ISSUE TITLE
Can not find new issue on es when using this plugin

### ISSUE THREAD

**Issue by Jeffsonery** [efigence/redmine_search#1]
hi~i found this plugin and was interested, so i tested it on my redmine 2.6
after reindexing, the searching function was working all right. but when i created a new issue, i couldn't find that new issue in my elasticsearch.
and i connot really understand how to 'switch search engine in Admin panel to Elasticsearch Engine'.
i know it's an old work to you but i am really interested in this plugin and really want it to work on my redmine system. so sorry for this sudden disturbing and hopping to receive your reply.
and many thanks to you.

**Comment by Jeffsonery** [comment]
i am not a native english speaker so sorry for my poor english orz

**Comment by Jeffsonery** [comment]
i am not a nataive English speaker and not good at English. also i am not very good at ruby, nor es. still a learner

**Comment by swiatkiewicz** [comment]
Hi @Jeffsonery,
I'm guessing that You do not have a background processing library installed.
Every newly created/updated or deleted record is reindexed asynchronously, so you need to have [Sidekiq](https://github.com/mperham/sidekiq) installed in your app.

**Comment by Jeffsonery** [comment]
hello @swiatkiewicz 
thank you very much for your reply
i've installed Sidekiq on my server, am i need to update data to es on my own? or is this plugin has already had its mechanisms to update automaticly when i create a new record while i just need to make it work?

**Comment by swiatkiewicz** [comment]
@Jeffsonery It should work out of the box.

You should be able to see this jobs at `/sidekiq`.

**Comment by Jeffsonery** [comment]
thanks again for your reply @swiatkiewicz 
sorry  for bothering you again... but i haven't seen any jobs running on the sidekiq webui while operating redmine issues. also my problem is still there: no newly created or modified record update on my es.
and i receive apache errorlogs when sidekiq webpage is Polling Interval every 2 sec.
[ 2018-08-08 09:17:26.3176 3352/7ffab955a700 agents/HelperAgent/RequestHandler.h:672 ]: [Client 23] Disconnecting with error: application response format error (invalid header)
[Wed Aug 08 09:17:26.317843 2018] [core:error] [pid 3431] [client 200.200.168.45:65053] End of script output before headers: sidekiq, referer: http://200.200.169.183/sidekiq/
tried some methods found on the internet but nothing changed. don't know what is going on...

**Comment by swiatkiewicz** [comment]
@Jeffsonery This is not issue of this plugin.
Do you have redis installed? Check your application logs for error details.

**Comment by Jeffsonery** [comment]
thank you for your patience. of course i installed redis for my sidekiq to work. i've found another way to achieve my goal. still love this plugin, gives me more ideas to think about. thank you.
